---
title: "Data Import"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
```

Import our first dataset

```{r}
litters_df = 
  read_csv(
    file = "data/FAS_litters.csv",
    na = c("", "NA", ".")
  )

litters_df = janitor:::clean_names(litters_df)
```

Import our second dataset

```{r}
pups_df = 
  read_csv(file= "data/FAS_pups.csv", 
           skip = 3,
          na = c("", "NA", ".")
  )

pups_df = janitor:::clean_names(pups_df)
```

## Look at the data

```{r}
litters_df
pups_df
```

Head or Tails

```{r}
head(litters_df, 20)

tail(pups_df, 5)
```

Skimming??

```{r}
skimr::skim(pups_df)
```

## Oh excel...

Jenny Bryan made 'readxl' to solve our problems. 

```{r}
mlb_df = 
  read_excel("data/mlb11.xlsx")
```

Look at the data!

```{r}
mlb_df
```

Load  some of the LotR data.

Import FOTR Words

```{r}
fotr_df = 
  read_excel(
    "data/LotR_Words.xlsx",
    range = "B3:D6"
  )
```

Import TT Words

```{r}
tt_df = 
  read_excel(
    "data/LotR_Words.xlsx",
    range = "F3:H6"
  )
```

